### ISSUE TITLE
Posting image public on dockerhub is highly not recommended for "secret" tasks :) 

### ISSUE THREAD

**Issue by polsevev** [fribyte-code/friByte.capture-the-flag#25]

**Comment by mathiash98** [comment]
Could you describe why it is a problem? The dockerImage to dockerHub does not contain secret information? It's the same as the source code here in GitHub which is public

**Comment by polsevev** [comment]
Well, lol ur prolly right, tenkte ikke på at databasen er separat xDDDDDDDDDDDDDDDDDDDDDDDD
