### ISSUE TITLE
Host an instance for HeltSikker somewhere

### ISSUE THREAD

**Issue by mathiash98** [fribyte-code/friByte.capture-the-flag#27]
Heltsikker will arrange a CTF 2024-02-23 with this software. We need to spin up an instance of the software on some domain for them.

**Comment by polsevev** [comment]
Wow, er de sikkre på dette?

**Comment by mathiash98** [comment]
> Wow, er de sikkre på dette?

See meeting notes from @skivdal on Mattermost

**Comment by skivdal** [comment]
> Wow, er de sikkre på dette?

*Helt* sikre lol

**Comment by mathiash98** [comment]
Done, it was a success
