### ISSUE TITLE
Task Category

### ISSUE THREAD

**Issue by mathiash98** [fribyte-code/friByte.capture-the-flag#30]
Put tasks into categories for easier filtering, organizing etc.

In Backend:
1. Extend `CtfTask` and `CtfTaskReadModel` to contain a `Category` string field.
     - We can also introduce a Category DbModel, but it is strictly not needed
2. Add an endpoint in TasksController to fetch all categories a list of strings
3. Run a new Entity Framework Database migration, check readme file for instructions

In Frontend:
1. In order to prevent misspellings etc. We should have a field in the admin panel pre-filled with all existing categories. So fetch these categories from the newly created categories endpoint
2. Then we should group the list of tasks in each category in the main page. -> You can do this in a separate task

**Comment by simsine** [comment]
> 2\. Add an endpoint in TasksController to fetch all categories a list of strings

Kan hende jeg er dum, men hvor er dette endepunktet?

**Comment by mathiash98** [comment]
> > 2. Add an endpoint in TasksController to fetch all categories a list of strings
> 
> Kan hende jeg er dum, men hvor er dette endepunktet?

Oja glemte å lage det, kan fikse

**Comment by mathiash98** [comment]
> > > 2. Add an endpoint in TasksController to fetch all categories a list of strings
> > 
> > 
> > Kan hende jeg er dum, men hvor er dette endepunktet?
> 
> Oja glemte å lage det, kan fikse

Adda no til din branch

**Comment by simsine** [comment]
> > > > 2. Add an endpoint in TasksController to fetch all categories a list of strings
> > > 
> > > 
> > > Kan hende jeg er dum, men hvor er dette endepunktet?
> > 
> > 
> > Oja glemte å lage det, kan fikse
> 
> Adda no til din branch

cool

**Comment by mathiash98** [comment]
> So far så gir ikke api-et noe respons, kanskje fordi prod API-et ikke har det ennå? Jeg kan alternativt kjøre det lokalt men det er ork :)

Stemmer det ja, kan lage en commit og PR mot main branch med funksjonen

**Comment by simsine** [comment]
Det ville vært veldig cash money av deg 🙏

**Comment by mathiash98** [comment]
> Det ville vært veldig cash money av deg 🙏

https://github.com/fribyte-code/friByte.capture-the-flag/pull/42

**Comment by simsine** [comment]
🦅🗣️🗣️🗣️🔥🔥🦅🚨🦅🦅🦅🚨🔥
